### PR TITLE
V3

### PR DESCRIPTION
**Pull request by sum01**
So I completely understand if you don't want to merge this, as I basically rewrote the whole thing.

Note that while this PR requires Micro >= v1.3.5, I kept the old version in the `repo.json` so that people not on v1.3.5 can still use the previous version.

---
Anyways, this PR brings:

### Fixes
* #13 
* #14 
* #15 
* #19 
* #20 
* The broken syntax highlighting.

### Adds
* Directory minimizing/maximizing, without moving into them, by nesting the content below the dir.
* File/directory renaming, creation, & deletion.
* An editorconfig file of my own preference, since no one responded to #15 
* Safe functions for all actions so any/all actions can be rebound by the end-user.

### Changes
* To read-only, so you can't mess with the tree.
* Some keybindings to work safely with the tree view (read-only doesn't magically fix everything).
* The `Enter` keybind was changed to `Tab` because read-only disables the enter key.
* The example picture, so that it shows the new dir content nesting feature.
* The README, so that the user can glean everything the plugin offers easily.

### Removed
* Most keybindings that normally cause issues.
* The pointless gitignore.

---

I'm aware there's some dead code, and other little general weirdness, but I figure that for the most part my branch is finished. Sure things could be more clean and whatnot, but something > nothing.

### CODE REVIEW

**Comment by tommyshem** [comment]
Looks good but there is a problem with the left mouse clicking on long lists. (does not open or opens the wrong filename.) Needs looking in to.
@NicolaiSoeborg A lot of good features added, I have no problems with the pull request when mouse bug is fixed.

**Comment by sum01** [comment]
@tommyshem The exact issue is here https://github.com/sum01/filemanager-plugin/issues/8
I don't know of a fix for it, and zyedidia didn't respond when I pinged him on Gitter about it.

**Comment by sum01** [comment]
The mouseclick issue is fixed.

**Comment by tommyshem** [comment]
@NicolaiSoeborg Can be pulled in if you are happy with it.

**Pull request merged**
