### PR TITLE
Add proper way to install plugin in README

### PR DESCRIPTION
**Pull request by sum01**
By adding the repo to `pluginrepos`, the user can use `plugin install filemanager` and `plugin update` to install/update your plugin.

### CODE REVIEW

**Comment by tommyshem** [comment]
Looks good. Tested working ok. We could have both methods in the README file, for any one wanting to work on the prject for testing and sending pull requests.

**Comment by sum01** [comment]
If desired, I could add an `# Installation` section & add both options. I just found this solution in the micro docs, so figured I'd submit a PR.

**Comment by tommyshem** [comment]
The filemanager has been added to the micro-editor plugin-channel 45 mins ago so this might not be needed now as it can be installed from the micro editor plugin repo by default. https://github.com/micro-editor/plugin-channel/pull/20

**Comment by sum01** [comment]
Yeah, I just saw that. Could probably replace all the install info with just `plugin install filemanager` now.

**Comment by tommyshem** [comment]
Yes it should work with the above command, but I have not tested to see if it works.

**Comment by NicolaiSoeborg** [comment]
Thanks for the PR, merged!

**Pull request merged**
